# Generated by Django 3.1.4 on 2020-12-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(),
        ),
    ]
