# Generated by Django 3.1.4 on 2020-12-16 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_survey', '0002_auto_20201216_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='Ответ')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_survey.question')),
            ],
        ),
    ]
